### PR TITLE
Require Java 11 or newer

### LINKED ISSUE #38: Missing compatibility with Java 17
The package `com.sun.javadoc.*` has been deprecated for removal since Java 9, in favor of `jdk.javadoc.doclet.*`, which was introduced in the same release. We're using the sun classes in `TagXMLDoclet` still:
https://github.com/jenkinsci/maven-jellydoc-plugin/blob/b175cdffa6e69fb1eddca77efd7b00cd194b84e4/maven-jellydoc-plugin/src/main/java/org/jvnet/maven/jellydoc/TagXMLDoclet.java#L18-L30
If I recall correctly, they have been removed in Java 12 or 13. Therefore, using tasks looking for `com.sun.javadoc.*`, are failing on Java 17.

Given, we require Java 11 as baseline, we can safely make use of the new doclet API and get a rid of the sun one, to ensure this plugin's functionality is warranted on modern Java versions too.

### PR DESCRIPTION
**Pull request by basil**
Fixes #38. Migrates away from the Java 8 Javadoc API to the Java 9+ Javadoc API. I could not find any reference material online; this was all learned as I went.

### Testing done

Ran the Mojo before and after this change against Jelly; verified that the generated taglibs looked right.

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by basil** [comment]
@NotMyFault Are you interested in helping me test this? Would be great to run core taglib generation against this change and verify that the taglibs look right (or at least no worse than before).

File: jellydoc-maven-plugin/src/main/java/org/jvnet/maven/jellydoc/TagXMLDoclet.java [hunk 1]
```diff
@@ -61,14 +73,16 @@
...
+public class TagXMLDoclet implements Doclet {
+
+    private DocTrees docTrees;
+    private Reporter reporter;
 
     private String targetFileName = null;
     private String encodingFormat;
 
-    public TagXMLDoclet (RootDoc root) throws Exception
+    private void main(DocletEnvironment root) throws Exception
```
Comment (basil) [inline jellydoc-maven-plugin/src/main/java/org/jvnet/maven/jellydoc/TagXMLDoclet.java:84]: Good luck trying to understand the changes to this file. The only [migration guide](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.javadoc/jdk/javadoc/doclet/package-summary.html#migration) that exists has almost zero information other than the package changes. I had to figure out all of the semantic changes by trial and error.

**Comment by NotMyFault** [comment]
> NotMyFault Are you interested in helping me test this? Would be great to run core taglib generation against this change and verify that the taglibs look right (or at least no worse than before).

Surely, I created https://github.com/NotMyFault/jenkins/tree/jellydoc-11 with an incremental of maven-stapler-plugin using an incremental of this PR.
To generate the site, I ran `cd core/ ; mvn --show-version --batch-mode -DgenerateProjectInfo=false -DgenerateSitemap=false -e clean site:site`:
Screenshot 2023-07-11 at 08 55 35

The generated page looks like https://reports.jenkins.io/core-taglib/jelly-taglib-ref.html

File: .github/workflows/site.yml [hunk 2]
```diff
@@ -28,7 +28,7 @@ jobs:
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
-          java-version: '8'
+          java-version: '11'
```
Comment (NotMyFault) [inline .github/workflows/site.yml:31]: We probably can use 17 too, no?

**Review by NotMyFault — APPROVED** [review]
No objections from me to not move on 🚀

File: .github/workflows/site.yml (hunk 2 above)
Comment (basil) [reply .github/workflows/site.yml:31]: We could, but that would be inconsistent with the Stapler and HPI Maven plugins.
